name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      COVERAGE_MIN: "70"     # single source of truth
      PIP_CACHE_DIR: ~/.cache/pip
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.lock ]; then
            pip install -r requirements.lock
          else
            pip install -r requirements.txt
          fi
          python -m playwright install --with-deps

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Unit tests (coverage gate + HTML)
        run: |
          pytest backend/tests/unit             --maxfail=1             --cov=backend             --cov-report=xml             --cov-report=html             --cov-report=term-missing             --cov-fail-under=$COVERAGE_MIN

      - name: API tests
        run: pytest -q backend/tests/api --maxfail=1

      - name: E2E tests (headless)
        env:
          HEADLESS: "true"
        run: pytest -q backend/tests/e2e/test_login_playwright.py --maxfail=1

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/**
          if-no-files-found: error
